// Woordenschat per categorie
const VOCABULARY = {
  eten: [
    { nl: 'het brood', it: 'il pane', example: 'Voglio del pane.' },
    { nl: 'de pasta', it: 'la pasta', example: 'La pasta è buona.' },
    { nl: 'de pizza', it: 'la pizza', example: 'Una pizza, per favore.' },
    { nl: 'de wijn', it: 'il vino', example: 'Un bicchiere di vino.' },
    { nl: 'het water', it: 'l\'acqua', example: 'Acqua minerale.' },
    { nl: 'de koffie', it: 'il caffè', example: 'Un caffè, per favore.' },
    { nl: 'het ijs', it: 'il gelato', example: 'Il gelato al cioccolato.' },
    { nl: 'de kaas', it: 'il formaggio', example: 'Formaggio parmigiano.' },
    { nl: 'het vlees', it: 'la carne', example: 'La carne è fresca.' },
    { nl: 'de vis', it: 'il pesce', example: 'Il pesce del lago.' },
    { nl: 'het fruit', it: 'la frutta', example: 'La frutta è dolce.' },
    { nl: 'de tomaat', it: 'il pomodoro', example: 'Pomodori freschi.' },
    { nl: 'het ontbijt', it: 'la colazione', example: 'La colazione è pronta.' },
    { nl: 'de lunch', it: 'il pranzo', example: 'Il pranzo è alle dodici.' },
    { nl: 'het diner', it: 'la cena', example: 'La cena è alle otto.' },
    { nl: 'de suiker', it: 'lo zucchero', example: 'Un po\' di zucchero, grazie.' },
    { nl: 'het zout', it: 'il sale', example: 'Passami il sale.' },
    { nl: 'de peper', it: 'il pepe', example: 'Un po\' di pepe nero.' },
    { nl: 'de olie', it: 'l\'olio', example: 'Olio d\'oliva extra vergine.' },
    { nl: 'de melk', it: 'il latte', example: 'Un caffè con latte.' },
    { nl: 'het ei', it: 'l\'uovo', example: 'Le uova fresche.' },
    { nl: 'de groente', it: 'la verdura', example: 'Mangio molta verdura.' },
    { nl: 'de aardappel', it: 'la patata', example: 'Patate al forno.' },
    { nl: 'de ui', it: 'la cipolla', example: 'Una cipolla rossa.' },
    { nl: 'de knoflook', it: 'l\'aglio', example: 'Un po\' di aglio.' },
    { nl: 'het toetje', it: 'il dolce', example: 'Un dolce delizioso.' },
    { nl: 'de soep', it: 'la zuppa', example: 'La zuppa è calda.' },
    { nl: 'de salade', it: 'l\'insalata', example: 'Un\'insalata fresca.' },
    { nl: 'het restaurant', it: 'il ristorante', example: 'Un ristorante sul lago.' },
    { nl: 'de rekening', it: 'il conto', example: 'Il conto, per favore.' },
  ],
  reizen: [
    { nl: 'het meer', it: 'il lago', example: 'Il lago di Como è bellissimo.' },
    { nl: 'de berg', it: 'la montagna', example: 'Le montagne delle Dolomiti.' },
    { nl: 'de stad', it: 'la città', example: 'Una bella città.' },
    { nl: 'het hotel', it: 'l\'albergo', example: 'L\'albergo è vicino al lago.' },
    { nl: 'het station', it: 'la stazione', example: 'La stazione di Milano.' },
    { nl: 'de trein', it: 'il treno', example: 'Il treno parte alle otto.' },
    { nl: 'het strand', it: 'la spiaggia', example: 'La spiaggia del lago.' },
    { nl: 'het dorp', it: 'il paese', example: 'Un piccolo paese.' },
    { nl: 'de kerk', it: 'la chiesa', example: 'Una chiesa antica.' },
    { nl: 'het kasteel', it: 'il castello', example: 'Il castello sul lago.' },
    { nl: 'de ferry', it: 'il traghetto', example: 'Il traghetto per Bellagio.' },
    { nl: 'de haven', it: 'il porto', example: 'Il porto di Varenna.' },
    { nl: 'de kaart', it: 'la mappa', example: 'Ho bisogno di una mappa.' },
    { nl: 'het paspoort', it: 'il passaporto', example: 'Il mio passaporto, prego.' },
    { nl: 'de koffer', it: 'la valigia', example: 'La mia valigia è pesante.' },
    { nl: 'het vliegtuig', it: 'l\'aereo', example: 'L\'aereo parte alle nove.' },
    { nl: 'de auto', it: 'la macchina', example: 'La macchina è parcheggiata.' },
    { nl: 'de fiets', it: 'la bicicletta', example: 'Un giro in bicicletta.' },
    { nl: 'de weg', it: 'la strada', example: 'Questa strada porta al lago.' },
    { nl: 'de brug', it: 'il ponte', example: 'Il ponte sul fiume.' },
    { nl: 'het plein', it: 'la piazza', example: 'La piazza del paese.' },
    { nl: 'het museum', it: 'il museo', example: 'Visitiamo il museo.' },
    { nl: 'de markt', it: 'il mercato', example: 'Il mercato del sabato.' },
    { nl: 'de gids', it: 'la guida', example: 'La nostra guida turistica.' },
    { nl: 'het uitzicht', it: 'la vista', example: 'Che bella vista sul lago!' },
    { nl: 'de excursie', it: 'la gita', example: 'Una gita in montagna.' },
    { nl: 'het kaartje', it: 'il biglietto', example: 'Un biglietto per il traghetto.' },
    { nl: 'de douane', it: 'la dogana', example: 'Passiamo la dogana.' },
    { nl: 'de reis', it: 'il viaggio', example: 'Buon viaggio!' },
    { nl: 'de vakantie', it: 'la vacanza', example: 'Una vacanza al lago.' },
  ],
  natuur: [
    { nl: 'het water', it: 'l\'acqua', example: 'L\'acqua è cristallina.' },
    { nl: 'de zon', it: 'il sole', example: 'Il sole splende.' },
    { nl: 'de lucht', it: 'il cielo', example: 'Il cielo è azzurro.' },
    { nl: 'de boom', it: 'l\'albero', example: 'Un albero d\'ulivo.' },
    { nl: 'de bloem', it: 'il fiore', example: 'I fiori sul lago.' },
    { nl: 'de rots', it: 'la roccia', example: 'Le rocce delle montagne.' },
    { nl: 'de rivier', it: 'il fiume', example: 'Il fiume scorre veloce.' },
    { nl: 'de wind', it: 'il vento', example: 'Il vento dal nord.' },
    { nl: 'de sneeuw', it: 'la neve', example: 'La neve sulle montagne.' },
    { nl: 'het bos', it: 'il bosco', example: 'Un bosco verde.' },
    { nl: 'de maan', it: 'la luna', example: 'La luna sul lago.' },
    { nl: 'de ster', it: 'la stella', example: 'Le stelle di notte.' },
    { nl: 'de wolk', it: 'la nuvola', example: 'Una nuvola bianca.' },
    { nl: 'de regen', it: 'la pioggia', example: 'La pioggia di primavera.' },
    { nl: 'het gras', it: 'l\'erba', example: 'L\'erba verde.' },
    { nl: 'het blad', it: 'la foglia', example: 'Le foglie d\'autunno.' },
    { nl: 'de vogel', it: 'l\'uccello', example: 'Un uccello canta.' },
    { nl: 'de vlinder', it: 'la farfalla', example: 'Una farfalla colorata.' },
    { nl: 'het dier', it: 'l\'animale', example: 'Un animale selvatico.' },
    { nl: 'de vallei', it: 'la valle', example: 'Una valle tra le montagne.' },
    { nl: 'het eiland', it: 'l\'isola', example: 'Un\'isola nel lago.' },
    { nl: 'de golf', it: 'l\'onda', example: 'Le onde del lago.' },
    { nl: 'de kust', it: 'la costa', example: 'La costa del lago.' },
    { nl: 'de grot', it: 'la grotta', example: 'Una grotta nella montagna.' },
    { nl: 'het pad', it: 'il sentiero', example: 'Un sentiero in montagna.' },
    { nl: 'de top', it: 'la cima', example: 'La cima della montagna.' },
    { nl: 'de bron', it: 'la sorgente', example: 'Una sorgente d\'acqua.' },
    { nl: 'de schaduw', it: 'l\'ombra', example: 'L\'ombra dell\'albero.' },
    { nl: 'de horizon', it: 'l\'orizzonte', example: 'L\'orizzonte sul lago.' },
    { nl: 'de natuur', it: 'la natura', example: 'Amo la natura.' },
  ],
  basis: [
    { nl: 'goedemorgen', it: 'buongiorno', example: 'Buongiorno, come stai?' },
    { nl: 'goedenavond', it: 'buonasera', example: 'Buonasera a tutti.' },
    { nl: 'tot ziens', it: 'arrivederci', example: 'Arrivederci, a presto!' },
    { nl: 'alsjeblieft', it: 'per favore', example: 'Un caffè, per favore.' },
    { nl: 'dank je wel', it: 'grazie', example: 'Grazie mille!' },
    { nl: 'ja', it: 'sì', example: 'Sì, certo!' },
    { nl: 'nee', it: 'no', example: 'No, grazie.' },
    { nl: 'mooi', it: 'bello/bella', example: 'Che bella vista!' },
    { nl: 'groot', it: 'grande', example: 'Un grande lago.' },
    { nl: 'klein', it: 'piccolo/a', example: 'Un piccolo paese.' },
    { nl: 'ik heet', it: 'mi chiamo', example: 'Mi chiamo Marco.' },
    { nl: 'hoe gaat het', it: 'come stai', example: 'Come stai oggi?' },
    { nl: 'sorry', it: 'mi dispiace', example: 'Mi dispiace tanto.' },
    { nl: 'pardon', it: 'scusi', example: 'Scusi, dov\'è la stazione?' },
    { nl: 'misschien', it: 'forse', example: 'Forse domani.' },
    { nl: 'altijd', it: 'sempre', example: 'Vengo sempre qui.' },
    { nl: 'nooit', it: 'mai', example: 'Non vado mai lì.' },
    { nl: 'vandaag', it: 'oggi', example: 'Oggi fa bel tempo.' },
    { nl: 'morgen', it: 'domani', example: 'A domani!' },
    { nl: 'gisteren', it: 'ieri', example: 'Ieri ho visitato il lago.' },
    { nl: 'hier', it: 'qui', example: 'Vieni qui.' },
    { nl: 'daar', it: 'là', example: 'Il lago è là.' },
    { nl: 'goed', it: 'bene', example: 'Sto bene, grazie.' },
    { nl: 'slecht', it: 'male', example: 'Non mi sento male.' },
    { nl: 'snel', it: 'veloce', example: 'Un treno veloce.' },
    { nl: 'langzaam', it: 'lento', example: 'Cammina lento.' },
    { nl: 'warm', it: 'caldo', example: 'Fa caldo oggi.' },
    { nl: 'koud', it: 'freddo', example: 'L\'acqua è fredda.' },
    { nl: 'nieuw', it: 'nuovo', example: 'Un vestito nuovo.' },
    { nl: 'oud', it: 'vecchio', example: 'Un castello vecchio.' },
  ],
  getallen: [
    { nl: 'één', it: 'uno', example: 'Uno, due, tre...' },
    { nl: 'twee', it: 'due', example: 'Due caffè, per favore.' },
    { nl: 'drie', it: 'tre', example: 'Tre giorni.' },
    { nl: 'vier', it: 'quattro', example: 'Quattro stagioni.' },
    { nl: 'vijf', it: 'cinque', example: 'Cinque euro.' },
    { nl: 'zes', it: 'sei', example: 'Sei ore.' },
    { nl: 'zeven', it: 'sette', example: 'Sette giorni.' },
    { nl: 'acht', it: 'otto', example: 'Otto persone.' },
    { nl: 'negen', it: 'nove', example: 'Nove mesi.' },
    { nl: 'tien', it: 'dieci', example: 'Dieci euro.' },
    { nl: 'twintig', it: 'venti', example: 'Venti minuti.' },
    { nl: 'honderd', it: 'cento', example: 'Cento chilometri.' },
    { nl: 'elf', it: 'undici', example: 'Undici anni.' },
    { nl: 'twaalf', it: 'dodici', example: 'Dodici mesi.' },
    { nl: 'dertien', it: 'tredici', example: 'Tredici euro.' },
    { nl: 'veertien', it: 'quattordici', example: 'Quattordici giorni.' },
    { nl: 'vijftien', it: 'quindici', example: 'Quindici minuti.' },
    { nl: 'zestien', it: 'sedici', example: 'Sedici anni.' },
    { nl: 'zeventien', it: 'diciassette', example: 'Diciassette persone.' },
    { nl: 'achttien', it: 'diciotto', example: 'Diciotto euro.' },
    { nl: 'negentien', it: 'diciannove', example: 'Diciannove gradi.' },
    { nl: 'dertig', it: 'trenta', example: 'Trenta minuti.' },
    { nl: 'veertig', it: 'quaranta', example: 'Quaranta euro.' },
    { nl: 'vijftig', it: 'cinquanta', example: 'Cinquanta chilometri.' },
    { nl: 'zestig', it: 'sessanta', example: 'Sessanta secondi.' },
    { nl: 'zeventig', it: 'settanta', example: 'Settanta anni.' },
    { nl: 'tachtig', it: 'ottanta', example: 'Ottanta euro.' },
    { nl: 'negentig', it: 'novanta', example: 'Novanta gradi.' },
    { nl: 'duizend', it: 'mille', example: 'Mille grazie.' },
    { nl: 'miljoen', it: 'milione', example: 'Un milione di stelle.' },
  ],
  kleuren: [
    { nl: 'rood', it: 'rosso', example: 'Una barca rossa.' },
    { nl: 'blauw', it: 'blu', example: 'Il lago è blu.' },
    { nl: 'groen', it: 'verde', example: 'Le colline verdi.' },
    { nl: 'geel', it: 'giallo', example: 'Il sole giallo.' },
    { nl: 'oranje', it: 'arancione', example: 'Un tramonto arancione.' },
    { nl: 'paars', it: 'viola', example: 'Un fiore viola.' },
    { nl: 'roze', it: 'rosa', example: 'Una casa rosa.' },
    { nl: 'bruin', it: 'marrone', example: 'Occhi marroni.' },
    { nl: 'zwart', it: 'nero', example: 'Un gatto nero.' },
    { nl: 'wit', it: 'bianco', example: 'La neve bianca.' },
    { nl: 'grijs', it: 'grigio', example: 'Un cielo grigio.' },
    { nl: 'goud', it: 'dorato', example: 'Un tramonto dorato.' },
    { nl: 'zilver', it: 'argento', example: 'Un anello d\'argento.' },
    { nl: 'lichtblauw', it: 'azzurro', example: 'Un cielo azzurro.' },
    { nl: 'donkerblauw', it: 'blu scuro', example: 'Acqua blu scuro.' },
    { nl: 'lichtgroen', it: 'verde chiaro', example: 'Erba verde chiaro.' },
    { nl: 'turkoois', it: 'turchese', example: 'Un lago turchese.' },
    { nl: 'beige', it: 'beige', example: 'Una camicia beige.' },
    { nl: 'de kleur', it: 'il colore', example: 'Che bel colore!' },
    { nl: 'helder', it: 'chiaro', example: 'Un colore chiaro.' },
    { nl: 'donker', it: 'scuro', example: 'Un colore scuro.' },
    { nl: 'levendig', it: 'vivace', example: 'Colori vivaci.' },
    { nl: 'pastel', it: 'pastello', example: 'Colori pastello.' },
    { nl: 'veelkleurig', it: 'colorato', example: 'Un mercato colorato.' },
    { nl: 'doorzichtig', it: 'trasparente', example: 'Acqua trasparente.' },
  ],
  familie: [
    { nl: 'de moeder', it: 'la madre', example: 'Mia madre cucina bene.' },
    { nl: 'de vader', it: 'il padre', example: 'Mio padre lavora molto.' },
    { nl: 'de zus', it: 'la sorella', example: 'La mia sorella maggiore.' },
    { nl: 'de broer', it: 'il fratello', example: 'Il mio fratello piccolo.' },
    { nl: 'de dochter', it: 'la figlia', example: 'La mia figlia studia.' },
    { nl: 'de zoon', it: 'il figlio', example: 'Il mio figlio gioca.' },
    { nl: 'de oma', it: 'la nonna', example: 'La nonna racconta storie.' },
    { nl: 'de opa', it: 'il nonno', example: 'Il nonno pesca al lago.' },
    { nl: 'de tante', it: 'la zia', example: 'Mia zia vive a Como.' },
    { nl: 'de oom', it: 'lo zio', example: 'Mio zio ha una barca.' },
    { nl: 'de neef', it: 'il cugino', example: 'Il mio cugino è simpatico.' },
    { nl: 'de nicht', it: 'la cugina', example: 'La mia cugina abita qui.' },
    { nl: 'de man', it: 'il marito', example: 'Mio marito cucina la pasta.' },
    { nl: 'de vrouw', it: 'la moglie', example: 'Sua moglie è italiana.' },
    { nl: 'de baby', it: 'il bambino', example: 'Il bambino dorme.' },
    { nl: 'het kind', it: 'la bambina', example: 'La bambina gioca felice.' },
    { nl: 'de familie', it: 'la famiglia', example: 'Tutta la famiglia è qui.' },
    { nl: 'de ouders', it: 'i genitori', example: 'I miei genitori vivono qui.' },
    { nl: 'de schoonmoeder', it: 'la suocera', example: 'La suocera è gentile.' },
    { nl: 'de schoonvader', it: 'il suocero', example: 'Il suocero è simpatico.' },
    { nl: 'de partner', it: 'il compagno', example: 'Il mio compagno di viaggio.' },
    { nl: 'de vriend', it: 'l\'amico', example: 'Un buon amico.' },
    { nl: 'de vriendin', it: 'l\'amica', example: 'La mia migliore amica.' },
    { nl: 'het gezin', it: 'il nucleo familiare', example: 'Un piccolo nucleo familiare.' },
    { nl: 'de bruiloft', it: 'il matrimonio', example: 'Il matrimonio sul lago.' },
  ],
  lichaamsdelen: [
    { nl: 'het hoofd', it: 'la testa', example: 'Mi fa male la testa.' },
    { nl: 'het haar', it: 'i capelli', example: 'Capelli lunghi.' },
    { nl: 'het oog', it: 'l\'occhio', example: 'Occhi azzurri.' },
    { nl: 'het oor', it: 'l\'orecchio', example: 'L\'orecchio sinistro.' },
    { nl: 'de neus', it: 'il naso', example: 'Un naso piccolo.' },
    { nl: 'de mond', it: 'la bocca', example: 'Apri la bocca.' },
    { nl: 'de tand', it: 'il dente', example: 'Mi fa male un dente.' },
    { nl: 'de hals', it: 'il collo', example: 'Una sciarpa al collo.' },
    { nl: 'de schouder', it: 'la spalla', example: 'La spalla destra.' },
    { nl: 'de arm', it: 'il braccio', example: 'Il braccio sinistro.' },
    { nl: 'de hand', it: 'la mano', example: 'Dammi la mano.' },
    { nl: 'de vinger', it: 'il dito', example: 'Un anello al dito.' },
    { nl: 'het been', it: 'la gamba', example: 'La gamba destra.' },
    { nl: 'de voet', it: 'il piede', example: 'I piedi nell\'acqua.' },
    { nl: 'de rug', it: 'la schiena', example: 'Mi fa male la schiena.' },
    { nl: 'de buik', it: 'la pancia', example: 'Ho mal di pancia.' },
    { nl: 'het hart', it: 'il cuore', example: 'Il cuore batte forte.' },
    { nl: 'de huid', it: 'la pelle', example: 'La pelle abbronzata.' },
    { nl: 'de knie', it: 'il ginocchio', example: 'Il ginocchio fa male.' },
    { nl: 'de elleboog', it: 'il gomito', example: 'Il gomito destro.' },
    { nl: 'de wenkbrauw', it: 'il sopracciglio', example: 'Le sopracciglia scure.' },
    { nl: 'de wimper', it: 'le ciglia', example: 'Lunghe ciglia.' },
    { nl: 'de kin', it: 'il mento', example: 'Il mento appuntito.' },
    { nl: 'de wang', it: 'la guancia', example: 'Un bacio sulla guancia.' },
    { nl: 'de lip', it: 'il labbro', example: 'Le labbra rosse.' },
  ],
  kleding: [
    { nl: 'het shirt', it: 'la maglietta', example: 'Una maglietta blu.' },
    { nl: 'de broek', it: 'i pantaloni', example: 'Pantaloni neri.' },
    { nl: 'de jurk', it: 'il vestito', example: 'Un bel vestito.' },
    { nl: 'de rok', it: 'la gonna', example: 'Una gonna lunga.' },
    { nl: 'de jas', it: 'la giacca', example: 'Una giacca calda.' },
    { nl: 'de trui', it: 'il maglione', example: 'Un maglione di lana.' },
    { nl: 'de schoenen', it: 'le scarpe', example: 'Scarpe comode.' },
    { nl: 'de sokken', it: 'i calzini', example: 'Calzini caldi.' },
    { nl: 'de hoed', it: 'il cappello', example: 'Un cappello da sole.' },
    { nl: 'de sjaal', it: 'la sciarpa', example: 'Una sciarpa di seta.' },
    { nl: 'de handschoenen', it: 'i guanti', example: 'Guanti d\'inverno.' },
    { nl: 'de riem', it: 'la cintura', example: 'Una cintura di pelle.' },
    { nl: 'het pak', it: 'l\'abito', example: 'Un abito elegante.' },
    { nl: 'de zwembroek', it: 'il costume da bagno', example: 'Il costume da bagno.' },
    { nl: 'de sandalen', it: 'i sandali', example: 'Sandali estivi.' },
    { nl: 'de laarzen', it: 'gli stivali', example: 'Stivali da pioggia.' },
    { nl: 'de bril', it: 'gli occhiali', example: 'Occhiali da sole.' },
    { nl: 'het ondergoed', it: 'la biancheria intima', example: 'Biancheria intima morbida.' },
    { nl: 'de pyjama', it: 'il pigiama', example: 'Un pigiama comodo.' },
    { nl: 'de regenjas', it: 'l\'impermeabile', example: 'Indosso l\'impermeabile.' },
    { nl: 'de stof', it: 'il tessuto', example: 'Un tessuto morbido.' },
    { nl: 'de maat', it: 'la taglia', example: 'Che taglia porti?' },
    { nl: 'de knoop', it: 'il bottone', example: 'Un bottone rotto.' },
    { nl: 'de rits', it: 'la cerniera', example: 'La cerniera è bloccata.' },
    { nl: 'de zak', it: 'la tasca', example: 'Le chiavi sono in tasca.' },
  ],
  weer: [
    { nl: 'het weer', it: 'il tempo', example: 'Che tempo fa oggi?' },
    { nl: 'de temperatuur', it: 'la temperatura', example: 'La temperatura sale.' },
    { nl: 'warm', it: 'caldo', example: 'Fa molto caldo.' },
    { nl: 'koud', it: 'freddo', example: 'Fa freddo stamattina.' },
    { nl: 'de regen', it: 'la pioggia', example: 'La pioggia cade sul lago.' },
    { nl: 'de zon', it: 'il sole', example: 'C\'è il sole oggi.' },
    { nl: 'de wolk', it: 'la nuvola', example: 'Nuvole all\'orizzonte.' },
    { nl: 'de wind', it: 'il vento', example: 'C\'è molto vento.' },
    { nl: 'de storm', it: 'la tempesta', example: 'Una tempesta sul lago.' },
    { nl: 'de donder', it: 'il tuono', example: 'Ho sentito un tuono.' },
    { nl: 'de bliksem', it: 'il fulmine', example: 'Un fulmine in montagna.' },
    { nl: 'de mist', it: 'la nebbia', example: 'Nebbia sul lago stamattina.' },
    { nl: 'de hagel', it: 'la grandine', example: 'La grandine sulle montagne.' },
    { nl: 'het ijs', it: 'il ghiaccio', example: 'Il lago coperto di ghiaccio.' },
    { nl: 'de lente', it: 'la primavera', example: 'I fiori di primavera.' },
    { nl: 'de zomer', it: 'l\'estate', example: 'L\'estate sul lago.' },
    { nl: 'de herfst', it: 'l\'autunno', example: 'Le foglie d\'autunno.' },
    { nl: 'de winter', it: 'l\'inverno', example: 'La neve d\'inverno.' },
    { nl: 'bewolkt', it: 'nuvoloso', example: 'Oggi è nuvoloso.' },
    { nl: 'zonnig', it: 'soleggiato', example: 'Un giorno soleggiato.' },
    { nl: 'regenachtig', it: 'piovoso', example: 'Un weekend piovoso.' },
    { nl: 'de paraplu', it: 'l\'ombrello', example: 'Porta l\'ombrello.' },
    { nl: 'het seizoen', it: 'la stagione', example: 'La mia stagione preferita.' },
    { nl: 'het klimaat', it: 'il clima', example: 'Il clima del lago.' },
    { nl: 'de regenboog', it: 'l\'arcobaleno', example: 'Un arcobaleno sul lago.' },
  ],
};

// Werkwoorden met vervoegingen
const VERBS = [
  {
    infinitivo: 'essere',
    nl: 'zijn',
    type: 'onregelmatig',
    tenses: {
      presente: [
        { soggetto: 'io',    forma: 'sono',   nl: 'ik ben' },
        { soggetto: 'tu',    forma: 'sei',    nl: 'jij bent' },
        { soggetto: 'lui/lei', forma: 'è',    nl: 'hij/zij is' },
        { soggetto: 'noi',   forma: 'siamo',  nl: 'wij zijn' },
        { soggetto: 'voi',   forma: 'siete',  nl: 'jullie zijn' },
        { soggetto: 'loro',  forma: 'sono',   nl: 'zij zijn' },
      ],
      passato: [
        { soggetto: 'io',    forma: 'sono stato/a',   nl: 'ik ben geweest' },
        { soggetto: 'tu',    forma: 'sei stato/a',    nl: 'jij bent geweest' },
        { soggetto: 'lui/lei', forma: 'è stato/a',    nl: 'hij/zij is geweest' },
        { soggetto: 'noi',   forma: 'siamo stati/e',  nl: 'wij zijn geweest' },
        { soggetto: 'voi',   forma: 'siete stati/e',  nl: 'jullie zijn geweest' },
        { soggetto: 'loro',  forma: 'sono stati/e',   nl: 'zij zijn geweest' },
      ],
      futuro: [
        { soggetto: 'io',    forma: 'sarò',    nl: 'ik zal zijn' },
        { soggetto: 'tu',    forma: 'sarai',   nl: 'jij zult zijn' },
        { soggetto: 'lui/lei', forma: 'sarà',  nl: 'hij/zij zal zijn' },
        { soggetto: 'noi',   forma: 'saremo',  nl: 'wij zullen zijn' },
        { soggetto: 'voi',   forma: 'sarete',  nl: 'jullie zullen zijn' },
        { soggetto: 'loro',  forma: 'saranno', nl: 'zij zullen zijn' },
      ],
    },
  },
  {
    infinitivo: 'avere',
    nl: 'hebben',
    type: 'onregelmatig',
    tenses: {
      presente: [
        { soggetto: 'io',    forma: 'ho',      nl: 'ik heb' },
        { soggetto: 'tu',    forma: 'hai',     nl: 'jij hebt' },
        { soggetto: 'lui/lei', forma: 'ha',    nl: 'hij/zij heeft' },
        { soggetto: 'noi',   forma: 'abbiamo', nl: 'wij hebben' },
        { soggetto: 'voi',   forma: 'avete',   nl: 'jullie hebben' },
        { soggetto: 'loro',  forma: 'hanno',   nl: 'zij hebben' },
      ],
      passato: [
        { soggetto: 'io',    forma: 'ho avuto',     nl: 'ik heb gehad' },
        { soggetto: 'tu',    forma: 'hai avuto',    nl: 'jij hebt gehad' },
        { soggetto: 'lui/lei', forma: 'ha avuto',   nl: 'hij/zij heeft gehad' },
        { soggetto: 'noi',   forma: 'abbiamo avuto',nl: 'wij hebben gehad' },
        { soggetto: 'voi',   forma: 'avete avuto',  nl: 'jullie hebben gehad' },
        { soggetto: 'loro',  forma: 'hanno avuto',  nl: 'zij hebben gehad' },
      ],
      futuro: [
        { soggetto: 'io',    forma: 'avrò',    nl: 'ik zal hebben' },
        { soggetto: 'tu',    forma: 'avrai',   nl: 'jij zult hebben' },
        { soggetto: 'lui/lei', forma: 'avrà',  nl: 'hij/zij zal hebben' },
        { soggetto: 'noi',   forma: 'avremo',  nl: 'wij zullen hebben' },
        { soggetto: 'voi',   forma: 'avrete',  nl: 'jullie zullen hebben' },
        { soggetto: 'loro',  forma: 'avranno', nl: 'zij zullen hebben' },
      ],
    },
  },
  {
    infinitivo: 'andare',
    nl: 'gaan',
    type: 'onregelmatig',
    tenses: {
      presente: [
        { soggetto: 'io',    forma: 'vado',   nl: 'ik ga' },
        { soggetto: 'tu',    forma: 'vai',    nl: 'jij gaat' },
        { soggetto: 'lui/lei', forma: 'va',   nl: 'hij/zij gaat' },
        { soggetto: 'noi',   forma: 'andiamo',nl: 'wij gaan' },
        { soggetto: 'voi',   forma: 'andate', nl: 'jullie gaan' },
        { soggetto: 'loro',  forma: 'vanno',  nl: 'zij gaan' },
      ],
      passato: [
        { soggetto: 'io',    forma: 'sono andato/a',   nl: 'ik ben gegaan' },
        { soggetto: 'tu',    forma: 'sei andato/a',    nl: 'jij bent gegaan' },
        { soggetto: 'lui/lei', forma: 'è andato/a',    nl: 'hij/zij is gegaan' },
        { soggetto: 'noi',   forma: 'siamo andati/e',  nl: 'wij zijn gegaan' },
        { soggetto: 'voi',   forma: 'siete andati/e',  nl: 'jullie zijn gegaan' },
        { soggetto: 'loro',  forma: 'sono andati/e',   nl: 'zij zijn gegaan' },
      ],
      futuro: [
        { soggetto: 'io',    forma: 'andrò',   nl: 'ik zal gaan' },
        { soggetto: 'tu',    forma: 'andrai',  nl: 'jij zult gaan' },
        { soggetto: 'lui/lei', forma: 'andrà', nl: 'hij/zij zal gaan' },
        { soggetto: 'noi',   forma: 'andremo', nl: 'wij zullen gaan' },
        { soggetto: 'voi',   forma: 'andrete', nl: 'jullie zullen gaan' },
        { soggetto: 'loro',  forma: 'andranno',nl: 'zij zullen gaan' },
      ],
    },
  },
  {
    infinitivo: 'parlare',
    nl: 'spreken',
    type: '-are',
    tenses: {
      presente: [
        { soggetto: 'io',    forma: 'parlo',   nl: 'ik spreek' },
        { soggetto: 'tu',    forma: 'parli',   nl: 'jij spreekt' },
        { soggetto: 'lui/lei', forma: 'parla', nl: 'hij/zij spreekt' },
        { soggetto: 'noi',   forma: 'parliamo',nl: 'wij spreken' },
        { soggetto: 'voi',   forma: 'parlate', nl: 'jullie spreken' },
        { soggetto: 'loro',  forma: 'parlano', nl: 'zij spreken' },
      ],
      passato: [
        { soggetto: 'io',    forma: 'ho parlato',     nl: 'ik heb gesproken' },
        { soggetto: 'tu',    forma: 'hai parlato',    nl: 'jij hebt gesproken' },
        { soggetto: 'lui/lei', forma: 'ha parlato',   nl: 'hij/zij heeft gesproken' },
        { soggetto: 'noi',   forma: 'abbiamo parlato',nl: 'wij hebben gesproken' },
        { soggetto: 'voi',   forma: 'avete parlato',  nl: 'jullie hebben gesproken' },
        { soggetto: 'loro',  forma: 'hanno parlato',  nl: 'zij hebben gesproken' },
      ],
      futuro: [
        { soggetto: 'io',    forma: 'parlerò',   nl: 'ik zal spreken' },
        { soggetto: 'tu',    forma: 'parlerai',  nl: 'jij zult spreken' },
        { soggetto: 'lui/lei', forma: 'parlerà', nl: 'hij/zij zal spreken' },
        { soggetto: 'noi',   forma: 'parleremo', nl: 'wij zullen spreken' },
        { soggetto: 'voi',   forma: 'parlerete', nl: 'jullie zullen spreken' },
        { soggetto: 'loro',  forma: 'parleranno',nl: 'zij zullen spreken' },
      ],
    },
  },
  {
    infinitivo: 'mangiare',
    nl: 'eten',
    type: '-are',
    tenses: {
      presente: [
        { soggetto: 'io',    forma: 'mangio',   nl: 'ik eet' },
        { soggetto: 'tu',    forma: 'mangi',    nl: 'jij eet' },
        { soggetto: 'lui/lei', forma: 'mangia', nl: 'hij/zij eet' },
        { soggetto: 'noi',   forma: 'mangiamo', nl: 'wij eten' },
        { soggetto: 'voi',   forma: 'mangiate', nl: 'jullie eten' },
        { soggetto: 'loro',  forma: 'mangiano', nl: 'zij eten' },
      ],
      passato: [
        { soggetto: 'io',    forma: 'ho mangiato',     nl: 'ik heb gegeten' },
        { soggetto: 'tu',    forma: 'hai mangiato',    nl: 'jij hebt gegeten' },
        { soggetto: 'lui/lei', forma: 'ha mangiato',   nl: 'hij/zij heeft gegeten' },
        { soggetto: 'noi',   forma: 'abbiamo mangiato',nl: 'wij hebben gegeten' },
        { soggetto: 'voi',   forma: 'avete mangiato',  nl: 'jullie hebben gegeten' },
        { soggetto: 'loro',  forma: 'hanno mangiato',  nl: 'zij hebben gegeten' },
      ],
      futuro: [
        { soggetto: 'io',    forma: 'mangerò',   nl: 'ik zal eten' },
        { soggetto: 'tu',    forma: 'mangerai',  nl: 'jij zult eten' },
        { soggetto: 'lui/lei', forma: 'mangerà', nl: 'hij/zij zal eten' },
        { soggetto: 'noi',   forma: 'mangeremo', nl: 'wij zullen eten' },
        { soggetto: 'voi',   forma: 'mangerete', nl: 'jullie zullen eten' },
        { soggetto: 'loro',  forma: 'mangeranno',nl: 'zij zullen eten' },
      ],
    },
  },
  {
    infinitivo: 'volere',
    nl: 'willen',
    type: 'onregelmatig',
    tenses: {
      presente: [
        { soggetto: 'io',    forma: 'voglio',  nl: 'ik wil' },
        { soggetto: 'tu',    forma: 'vuoi',    nl: 'jij wilt' },
        { soggetto: 'lui/lei', forma: 'vuole', nl: 'hij/zij wil' },
        { soggetto: 'noi',   forma: 'vogliamo',nl: 'wij willen' },
        { soggetto: 'voi',   forma: 'volete',  nl: 'jullie willen' },
        { soggetto: 'loro',  forma: 'vogliono',nl: 'zij willen' },
      ],
      passato: [
        { soggetto: 'io',    forma: 'ho voluto',     nl: 'ik heb gewild' },
        { soggetto: 'tu',    forma: 'hai voluto',    nl: 'jij hebt gewild' },
        { soggetto: 'lui/lei', forma: 'ha voluto',   nl: 'hij/zij heeft gewild' },
        { soggetto: 'noi',   forma: 'abbiamo voluto',nl: 'wij hebben gewild' },
        { soggetto: 'voi',   forma: 'avete voluto',  nl: 'jullie hebben gewild' },
        { soggetto: 'loro',  forma: 'hanno voluto',  nl: 'zij hebben gewild' },
      ],
      futuro: [
        { soggetto: 'io',    forma: 'vorrò',   nl: 'ik zal willen' },
        { soggetto: 'tu',    forma: 'vorrai',  nl: 'jij zult willen' },
        { soggetto: 'lui/lei', forma: 'vorrà', nl: 'hij/zij zal willen' },
        { soggetto: 'noi',   forma: 'vorremo', nl: 'wij zullen willen' },
        { soggetto: 'voi',   forma: 'vorrete', nl: 'jullie zullen willen' },
        { soggetto: 'loro',  forma: 'vorranno',nl: 'zij zullen willen' },
      ],
    },
  },
  {
    infinitivo: 'potere',
    nl: 'kunnen',
    type: 'onregelmatig',
    tenses: {
      presente: [
        { soggetto: 'io',    forma: 'posso',   nl: 'ik kan' },
        { soggetto: 'tu',    forma: 'puoi',    nl: 'jij kunt' },
        { soggetto: 'lui/lei', forma: 'può',   nl: 'hij/zij kan' },
        { soggetto: 'noi',   forma: 'possiamo',nl: 'wij kunnen' },
        { soggetto: 'voi',   forma: 'potete',  nl: 'jullie kunnen' },
        { soggetto: 'loro',  forma: 'possono', nl: 'zij kunnen' },
      ],
      passato: [
        { soggetto: 'io',    forma: 'ho potuto',     nl: 'ik heb gekund' },
        { soggetto: 'tu',    forma: 'hai potuto',    nl: 'jij hebt gekund' },
        { soggetto: 'lui/lei', forma: 'ha potuto',   nl: 'hij/zij heeft gekund' },
        { soggetto: 'noi',   forma: 'abbiamo potuto',nl: 'wij hebben gekund' },
        { soggetto: 'voi',   forma: 'avete potuto',  nl: 'jullie hebben gekund' },
        { soggetto: 'loro',  forma: 'hanno potuto',  nl: 'zij hebben gekund' },
      ],
      futuro: [
        { soggetto: 'io',    forma: 'potrò',   nl: 'ik zal kunnen' },
        { soggetto: 'tu',    forma: 'potrai',  nl: 'jij zult kunnen' },
        { soggetto: 'lui/lei', forma: 'potrà', nl: 'hij/zij zal kunnen' },
        { soggetto: 'noi',   forma: 'potremo', nl: 'wij zullen kunnen' },
        { soggetto: 'voi',   forma: 'potrete', nl: 'jullie zullen kunnen' },
        { soggetto: 'loro',  forma: 'potranno',nl: 'zij zullen kunnen' },
      ],
    },
  },
  {
    infinitivo: 'venire',
    nl: 'komen',
    type: 'onregelmatig',
    tenses: {
      presente: [
        { soggetto: 'io',    forma: 'vengo',   nl: 'ik kom' },
        { soggetto: 'tu',    forma: 'vieni',   nl: 'jij komt' },
        { soggetto: 'lui/lei', forma: 'viene', nl: 'hij/zij komt' },
        { soggetto: 'noi',   forma: 'veniamo', nl: 'wij komen' },
        { soggetto: 'voi',   forma: 'venite',  nl: 'jullie komen' },
        { soggetto: 'loro',  forma: 'vengono', nl: 'zij komen' },
      ],
      passato: [
        { soggetto: 'io',    forma: 'sono venuto/a',   nl: 'ik ben gekomen' },
        { soggetto: 'tu',    forma: 'sei venuto/a',    nl: 'jij bent gekomen' },
        { soggetto: 'lui/lei', forma: 'è venuto/a',    nl: 'hij/zij is gekomen' },
        { soggetto: 'noi',   forma: 'siamo venuti/e',  nl: 'wij zijn gekomen' },
        { soggetto: 'voi',   forma: 'siete venuti/e',  nl: 'jullie zijn gekomen' },
        { soggetto: 'loro',  forma: 'sono venuti/e',   nl: 'zij zijn gekomen' },
      ],
      futuro: [
        { soggetto: 'io',    forma: 'verrò',   nl: 'ik zal komen' },
        { soggetto: 'tu',    forma: 'verrai',  nl: 'jij zult komen' },
        { soggetto: 'lui/lei', forma: 'verrà', nl: 'hij/zij zal komen' },
        { soggetto: 'noi',   forma: 'verremo', nl: 'wij zullen komen' },
        { soggetto: 'voi',   forma: 'verrete', nl: 'jullie zullen komen' },
        { soggetto: 'loro',  forma: 'verranno',nl: 'zij zullen komen' },
      ],
    },
  },
];

// SM-2 spaced repetition implementatie
const SM2 = {
  initialCard(word) {
    return { ...word, interval: 1, repetitions: 0, easeFactor: 2.5, nextReview: Date.now() };
  },
  review(card, quality) {
    // quality: 0=fout, 1=twijfel, 2=goed
    let { interval, repetitions, easeFactor } = card;
    const q = quality * 2.5; // schaal naar 0-5

    if (q < 3) {
      repetitions = 0;
      interval = 1;
    } else {
      if (repetitions === 0) interval = 1;
      else if (repetitions === 1) interval = 6;
      else interval = Math.round(interval * easeFactor);
      repetitions++;
    }

    easeFactor = Math.max(1.3, easeFactor + 0.1 - (5 - q) * (0.08 + (5 - q) * 0.02));
    const nextReview = Date.now() + interval * 24 * 60 * 60 * 1000;

    return { ...card, interval, repetitions, easeFactor, nextReview };
  },
};
